<?php
$menus = [['finder_folder', 'finder_folder'],['finder_folder_user', 'finder_folder_user'],['mod_banner', 'mod_banner'],['mod_bannerclient', 'mod_bannerclient'],['sys_catalog', 'sys_catalog'],['sys_domain', 'sys_domain'],['sys_function', 'sys_function'],['sys_module', 'sys_module'],['sys_nationality', 'sys_nationality'],['sys_rol', 'sys_rol'],['sys_rol_function', 'sys_rol_function'],['sys_rol_module', 'sys_rol_module'],['sys_setting', 'sys_setting'],['sys_user', 'sys_user'],['sys_user_grales', 'sys_user_grales'],
];
?>
<ul class="nav flex-column">
    <?php foreach ($menus as $m) : ?>
        <li class="nav-item">
            <a class="nav-link" href="<?= base_url() . '/' . $m[0] ?>"> <?= $m[1] ?></a>
        </li>
    <?php endforeach; ?>
</ul>



<?php 
/* End of file views/layout/sidebar.php */
/* Location: ./app/views/layout */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2022-02-26 02:45:16 */
?>